In [26]:
import os
from PIL import Image
import numpy as np
import cv2

4.1.0


In [2]:
path = 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset'
recognizer = cv2.face

In [4]:
def getImagesid(path):
    imagePaths = [os.path.join(path, f) for f in os.listdir(path)]
    print(imagePaths)
    faces = []
    ids = []
    for imagepath in imagePaths:
        faceImg = Image.open(imagepath).convert('L')
        faceNp = np.array(faceImg)
        Id = int(os.path.split(imagepath)[-1].split('.')[1])
        faces.append(faceNp)
        ids.append(Id)
        cv2.imshow("training_data", faceNp)
        cv2.waitKey(10)
        
    return ids, faces

faces, ids = getImagesid(path)

['C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.0.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.1.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.10.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.11.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.12.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.13.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.14.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.15.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.16.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.2.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.3.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.4.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.5.jpg', 'C:/

In [5]:
getImagesid(path)

['C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.0.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.1.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.10.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.11.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.12.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.13.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.14.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.15.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.16.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.2.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.3.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.4.jpg', 'C:/Users/square/Desktop/Face_Recognition_Detector/dataset\\users.1.5.jpg', 'C:/

([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [array([[ 92, 100,  93, ...,  97,  93,  97],
         [100,  90, 100, ...,  92, 101,  90],
         [ 95,  98, 167, ..., 164, 159,  97],
         ...,
         [ 97,  91, 146, ..., 139, 132,  94],
         [ 96,  98, 142, ..., 135, 144, 100],
         [ 95,  92,  98, ...,  93,  95,  96]], dtype=uint8),
  array([[ 97,  94,  96, ...,  96,  96,  94],
         [ 97,  96,  93, ...,  95,  96,  96],
         [ 94,  92,  76, ...,  75,  81,  91],
         ...,
         [ 97,  95,  64, ...,  71,  76,  95],
         [ 94,  91,  67, ...,  79,  79,  93],
         [ 96,  99,  94, ...,  96,  96, 101]], dtype=uint8),
  array([[ 95,  94,  96, ...,  94,  95,  94],
         [ 94,  97,  94, ...,  98,  94,  98],
         [ 98,  95, 145, ...,  47,  50,  93],
         ...,
         [ 96,  98,  30, ...,  84,  82,  96],
         [ 92,  95,  32, ...,  82,  83,  94],
         [ 99,  98,  95, ...,  97,  94,  98]], dtype=uint8),
  array([[ 96,  96,  98, ...,  

In [7]:
import cv2

In [8]:
cv2.__version__

'4.1.0'

In [19]:
import cv2

In [25]:
cv2.__version__

'4.1.0'

In [24]:
import cv2

In [22]:
!pip install opencv-contrib-python==3.4.3.18
